# Site settings
title: cici Blog
SEOTitle: cici的博客 | cici Blog
header-img: img/home-bg.jpeg
email: cicistream@outlook.com
description: "关于我自己 日常与记录，热情与爱 | 任梦溪，Web & Mobile Lover，Software Engineer | 这里是 @cicistream 的个人博客，与你一起发现更大的世界。"
keyword: "任梦溪, cicistream, cici, 前端, cicistream@outloo.com, @cicistream, 任梦溪的博客, cici Blog, 博客, 个人网站, 互联网, Web, JavaScript, 前端, 设计"
url: "https://cicistream.me"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username:     cicistream
zhihu_username:     cicistream
github_username:    cicistream
twitter_username:   cicistream
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]


# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: cici

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "For the next quantum leap<br>离开世界之前，一切都是过程"
sidebar-avatar: /img/header.png      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
    #     title: "Su",
    #     href: "http://su.gallery/"
    # },{
        title: "前端收藏夹",
        href: "http://collect.w3ctrain.com/"
    },{
        title: "阮一峰的个人网站",
        href: "http://www.ruanyifeng.com/home.html"
    },{
        title: "张鑫旭的博客",
        href: "https://www.zhangxinxu.com/"
    },{
        title: "Smashing-Magazine",
        href: "https://www.smashingmagazine.com/"
    },{
        title: "掘金",
        href: "https://juejin.im/"
    },{
        title: "segmentfault",
        href: "https://segmentfault.com/"
    }
]
